syntax = "proto3";

import "google/protobuf/empty.proto";

enum PermissionType {
  PERMISSION_TYPE_UNSPECIFIED = 0;
  PERMISSION_TYPE_MICROPHONE = 1;
  PERMISSION_TYPE_SPEECH_RECOGNITION = 2;
  PERMISSION_TYPE_ACCESSIBILITY = 3;
}

enum PermissionStatus {
  PERMISSION_STATUS_UNSPECIFIED = 0;
  PERMISSION_STATUS_GRANTED = 1;
  PERMISSION_STATUS_DENIED = 2;
  PERMISSION_STATUS_NOT_DETERMINED = 3;
}

message PermissionStatusProto {
  PermissionType   type   = 1;
  PermissionStatus status = 2;
}

message PermissionsStatusResponse {
  repeated PermissionStatusProto permissions = 1;
}

message PermissionTypeRequest {
  PermissionType type = 1;
}

service SystemPermissionsService {
  rpc GetPermissionsStatus(google.protobuf.Empty) returns (PermissionsStatusResponse);
  rpc OpenSystemSettings(PermissionTypeRequest) returns (google.protobuf.Empty);
  rpc RequestPermission(PermissionTypeRequest) returns (google.protobuf.Empty);
}
